### ISSUE TITLE
the search tab icon no longer overlaps with the demon ladder, but now overlaps with AREDL

### ISSUE THREAD

**Issue by MysticChromium** [loquibot/Integrated-Loquibot#3]
gotta move it down one more
![image](https://github.com/loquibot/Integrated-Loquibot/assets/82737960/41d2c495-5d21-4a20-9e3d-bff5d82dabdf)

**Comment by Alphalaneous** [comment]
This will be resolved when the Node IDs update comes out. I shouldn't have to be the one to account for all the other mods, we gotta work together. The Node IDs update will fix this by adding a layout to this menu for all the mods that use it to not have issues

**Comment by MysticChromium** [comment]
i see, ty for quick response

**Comment by Alphalaneous** [comment]
It should be resolved now
